name: langtrans
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  get: ^4.7.2
  camera: ^0.10.5+5
  permission_handler: ^11.0.1
  flutter_animate: ^4.3.0
  speech_to_text: ^7.0.0
  tflite_flutter: ^0.11.0
  path_provider: ^2.1.5
  image: ^3.3.0
  flutter_isolate: ^2.1.0
  vector_math: ^2.1.4
  async: ^2.11.0
  collection: ^1.17.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/hand_sign/
    - assets/asl_nn_model.tflite
    - assets/palm_detection_lite.tflite
    - assets/hand_landmark_full.tflite
